# Generated by Django 5.2.9 on 2026-01-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video_id', models.CharField(help_text='YouTube Video ID (e.g., rfscVS0vtbw)', max_length=50)),
                ('language', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('go', 'Go'), ('cpp', 'C++'), ('java', 'Java')], default='python', max_length=50)),
                ('initial_code', models.TextField(default='print("Hello World")')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
