# Generated by Django 5.2.9 on 2026-01-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video_id',
            field=models.CharField(max_length=255, verbose_name='YouTube URL or ID'),
        ),
    ]
