# Generated by Django 5.2.9 on 2026-01-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='initial_code',
            field=models.TextField(default='print("Hello Bro!")'),
        ),
    ]
