# Generated by Django 5.2.9 on 2026-01-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_initial_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video_id',
            field=models.CharField(max_length=500, verbose_name='YouTube Link or ID'),
        ),
    ]
