import type { Category, CategorySlug, LocalizedString, Product, ProductGender, Review } from '@/types';
import { toSlug } from '@/utils/format';

type VariantSeed = {
  label: LocalizedString;
  price: number;
  oldPrice: number | null;
  detail: LocalizedString;
  material: LocalizedString;
  care: LocalizedString;
  sizes: string[];
  colors: string[];
  stock: number;
  rating: number;
  reviewCount: number;
  tags: string[];
  images: number[];
};

type CategorySeed = {
  slug: CategorySlug;
  name: LocalizedString;
  description: LocalizedString;
  image: string;
  featured: boolean;
  imagePool: string[];
  variants: VariantSeed[];
};

const series = [
  {
    title: { en: 'ALEXANDRA LIMITED COLLECTION', ka: 'ALEXANDRA LIMITED COLLECTION' },
    tagline: {
      en: 'made with a clean shape, comfortable texture, and tidy finishing.',
      ka: 'შექმნილია სუფთა ფორმით, კომფორტული ტექსტურით და მოწესრიგებული დასრულებით.',
    },
  },
  {
    title: { en: 'Skyline Club', ka: 'სქაილაინ ქლაბი' },
    tagline: {
      en: 'shaped for city layering with relaxed structure and polished balance.',
      ka: 'შექმნილია ქალაქური ფენებისთვის, თავისუფალი სტრუქტურით და სუფთა ბალანსით.',
    },
  },
  {
    title: { en: 'After Hours', ka: 'აფთერ ჰაურსი' },
    tagline: {
      en: 'tuned for evening styling, tonal outfits, and confident minimalism.',
      ka: 'შექმნილია საღამოს სტილისთვის, ტონალური ლუქებისთვის და მშვიდი მინიმალიზმისთვის.',
    },
  },
  {
    title: { en: 'North Drift', ka: 'ნორთ დრიფტი' },
    tagline: {
      en: 'focused on comfort, movement, and layered utility for every day.',
      ka: 'ორიენტირებულია კომფორტზე, მოძრაობასა და ყოველდღიურ ფუნქციურ ფენებზე.',
    },
  },
  {
    title: { en: 'Solstice Line', ka: 'სოლსტის ლაინი' },
    tagline: {
      en: 'keeps a sharp look without making the outfit feel overdone.',
      ka: 'ინარჩუნებს მკაფიო იერს ზედმეტი ეფექტის გარეშე.',
    },
  },
] as const;

const imagePools: Record<CategorySlug, string[]> = {
  hoodies: [
    'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1523398002811-999ca8dec234?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1495121605193-b116b5b09a99?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1503342394128-c104d54dba01?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80',
  ],
  't-shirts': [
    'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?auto=format&fit=crop&w=1200&q=80',
  ],
  jeans: [
    'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1475180098004-ca77a66827be?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=1200&q=80',
  ],
  jackets: [
    'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1506629905607-d9c297d9d512?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1504593811423-6dd665756598?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=1200&q=80',
  ],
  pants: [
    'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1487412947147-5cebf100ffc2?auto=format&fit=crop&w=1200&q=80',
  ],
  shorts: [
    'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=1200&q=80',
  ],
  dresses: [
    'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=1200&q=80',
  ],
  accessories: [
    'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=80',
  ],
  shoes: [
    'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1514996937319-344454492b37?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1467043237213-65f2da53396f?auto=format&fit=crop&w=1200&q=80',
    'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=1200&q=80',
  ],
};

const categorySeeds: CategorySeed[] = [
  {
    slug: 'hoodies',
    name: { en: 'Hoodies', ka: 'ჰუდები' },
    description: {
      en: 'Soft fleece, relaxed fits, and easy layers for daily wear.',
      ka: 'რბილი ფლისი, მოდუნებული თარგები და მარტივი ფენები ყოველდღიური ტარებისთვის.',
    },
    image: imagePools.hoodies[0],
    featured: true,
    imagePool: imagePools.hoodies,
    variants: [
      {
        label: { en: 'Relaxed Hoodie', ka: 'მოდუნებული ჰუდი' },
        price: 189,
        oldPrice: 229,
        detail: {
          en: 'dropped shoulders, dense cuffs, and a brushed interior that keeps the shape crisp.',
          ka: 'დაშვებული მხრებით, მკვრივი მანჟეტებით და რბილი შიდა ფენით, რომელიც ფორმას გამოკვეთილს ტოვებს.',
        },
        material: {
          en: '420gsm brushed cotton fleece',
          ka: '420gsm დავარცხნილი ბამბის ფლისი',
        },
        care: {
          en: 'Machine wash cold, inside out, do not tumble dry.',
          ka: 'გარეცხე ცივად, შიგნიდან გადმობრუნებული; ნუ გამოიყენებ საშრობს.',
        },
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['Onyx', 'Stone', 'Clay'],
        stock: 8,
        rating: 4.9,
        reviewCount: 124,
        tags: ['hoodie', 'fleece', 'minimal'],
        images: [0, 1, 2],
      },
      {
        label: { en: 'Zip Hoodie', ka: 'ელვიანი ჰუდი' },
        price: 209,
        oldPrice: null,
        detail: {
          en: 'a double-layer hood, matte hardware, and a clean front zip for polished daily wear.',
          ka: 'ორმაგი კაპიუშონით, მქრქალი მეტალის დეტალებით და სუფთა წინა ელვით ყოველდღიური დახვეწილი ტარებისთვის.',
        },
        material: {
          en: 'Heavyweight cotton with soft loopback finish',
          ka: 'მძიმე ბამბა რბილი შიდა ტექსტურით',
        },
        care: {
          en: 'Wash with similar colors and reshape while damp.',
          ka: 'გარეცხე მსგავს ფერებთან ერთად და სველ მდგომარეობაში მიეცი ფორმა.',
        },
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Graphite', 'Ash', 'Ivory'],
        stock: 14,
        rating: 4.8,
        reviewCount: 87,
        tags: ['zip', 'layering', 'clean'],
        images: [1, 2, 3],
      },
      {
        label: { en: 'Washed Hoodie', ka: 'დამუშავებული ჰუდი' },
        price: 179,
        oldPrice: 215,
        detail: {
          en: 'pigment depth, a vintage handfeel, and tonal stitching that softens the entire look.',
          ka: 'პიგმენტური სიღრმით, ვინტაჟური შეხებით და ტონალური ნაკერებით, რომლებიც მთლიან ვიზუალს არბილებს.',
        },
        material: {
          en: 'Garment-washed cotton fleece',
          ka: 'დამუშავებული ბამბის ფლისი',
        },
        care: {
          en: 'Wash separately for the first cycle and avoid direct heat.',
          ka: 'პირველ რეცხვაზე გარეცხე ცალკე და მოერიდე პირდაპირ სიცხეს.',
        },
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Washed Black', 'Fade Olive', 'Dust Rose'],
        stock: 6,
        rating: 4.7,
        reviewCount: 52,
        tags: ['washed', 'streetwear', 'oversized'],
        images: [2, 3, 4],
      },
      {
        label: { en: 'Cropped Hoodie', ka: 'შემოკლებული ჰუდი' },
        price: 169,
        oldPrice: null,
        detail: {
          en: 'shortened proportions and a boxy drape that pairs naturally with high-rise bottoms.',
          ka: 'შემოკლებული პროპორციებით და ყუთისებრი დაცემით, რომელიც მაღალი წელის ქვედაბოლოებს ბუნებრივად ერწყმის.',
        },
        material: {
          en: 'Compact cotton blend fleece',
          ka: 'კომპაქტური ბამბის ნაზავი ფლისით',
        },
        care: {
          en: 'Cold wash and dry flat to preserve the cropped fit.',
          ka: 'გარეცხე ცივად და გააშრე სწორ ზედაპირზე, რომ ფორმა შენარჩუნდეს.',
        },
        sizes: ['XS', 'S', 'M', 'L'],
        colors: ['Cream', 'Jet', 'Mauve'],
        stock: 12,
        rating: 4.8,
        reviewCount: 69,
        tags: ['cropped', 'women', 'boxy'],
        images: [0, 3, 4],
      },
      {
        label: { en: 'Tech Hoodie', ka: 'ტექ ჰუდი' },
        price: 219,
        oldPrice: null,
        detail: {
          en: 'performance panels, hidden pockets, and sleek trim for a sharper utility mood.',
          ka: 'ფუნქციური პანელებით, დამალული ჯიბეებით და მკაფიო მოპირკეთებით უფრო ტექნიკური ხასიათისთვის.',
        },
        material: {
          en: 'Cotton-nylon stretch fleece',
          ka: 'ბამბა-ნეილონის გაწელვადი ფლისი',
        },
        care: {
          en: 'Wash cold and skip fabric softener.',
          ka: 'გარეცხე ცივად და არ გამოიყენო ქსოვილის დამარბილებელი.',
        },
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Carbon', 'Slate', 'Ice'],
        stock: 4,
        rating: 4.9,
        reviewCount: 41,
        tags: ['techwear', 'utility', 'daily'],
        images: [1, 3, 4],
      },
    ],
  },
  {
    slug: 't-shirts',
    name: { en: 'T-Shirts', ka: 'მაისურები' },
    description: {
      en: 'Clean T-shirts with useful weights, simple cuts, and comfortable collars.',
      ka: 'სუფთა მაისურები კარგი სისქით, მარტივი ჭრით და კომფორტული საყელოთი.',
    },
    image: imagePools['t-shirts'][0],
    featured: true,
    imagePool: imagePools['t-shirts'],
    variants: [
      {
        label: { en: 'Boxy Tee', ka: 'ბოქსი მაისური' },
        price: 89,
        oldPrice: null,
        detail: {
          en: 'extended sleeves and a boxy shape that still feels easy to wear.',
          ka: 'დაგრძელებული მკლავებით და ბოქსი ფორმით, რომელიც მაინც მარტივად ჩასაცმელია.',
        },
        material: { en: '280gsm combed cotton jersey', ka: '280gsm დავარცხნილი ბამბის ჯერსი' },
        care: { en: 'Cold wash, line dry, warm iron if needed.', ka: 'გარეცხე ცივად, გააშრე ჰაერზე, საჭიროების შემთხვევაში ოდნავ გააუთოე.' },
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['Black', 'Bone', 'Sage'],
        stock: 18,
        rating: 4.8,
        reviewCount: 156,
        tags: ['boxy', 'heavyweight', 'essential'],
        images: [0, 1, 2],
      },
      {
        label: { en: 'Heavyweight Tee', ka: 'მკვრივი მაისური' },
        price: 99,
        oldPrice: 119,
        detail: {
          en: 'dense cotton body and compact neckline that stay structured after repeat wear.',
          ka: 'მკვრივი ბამბის სხეულით და კომპაქტური ყელით, რომელიც ხშირი ტარების შემდეგაც ფორმას ინარჩუნებს.',
        },
        material: { en: '320gsm combed cotton', ka: '320gsm დავარცხნილი ბამბა' },
        care: { en: 'Wash inside out and avoid bleach.', ka: 'გარეცხე შიგნიდან გადმობრუნებული და მოერიდე გამათეთრებელს.' },
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Onyx', 'Oat', 'Steel'],
        stock: 9,
        rating: 4.9,
        reviewCount: 112,
        tags: ['heavyweight', 'clean', 'core'],
        images: [1, 2, 3],
      },
      {
        label: { en: 'Logo Tee', ka: 'ლოგო მაისური' },
        price: 95,
        oldPrice: null,
        detail: {
          en: 'minimal chest branding and softened shoulders for a clean everyday look.',
          ka: 'მინიმალური გულმკერდის ბრენდირებით და რბილი მხრის ხაზით სუფთა ყოველდღიური იერისთვის.',
        },
        material: { en: 'Soft-touch cotton jersey', ka: 'რბილი შეხების ბამბის ჯერსი' },
        care: { en: 'Machine wash cold and dry in shade.', ka: 'გარეცხე ცივად და გააშრე ჩრდილში.' },
        sizes: ['XS', 'S', 'M', 'L'],
        colors: ['Ivory', 'Jet', 'Sand'],
        stock: 15,
        rating: 4.7,
        reviewCount: 75,
        tags: ['logo', 'minimal', 'street'],
        images: [0, 2, 4],
      },
      {
        label: { en: 'Washed Tee', ka: 'დამუშავებული მაისური' },
        price: 92,
        oldPrice: 108,
        detail: {
          en: 'subtle fading and a lived-in finish that makes tonal outfits feel less formal.',
          ka: 'რბილი გახუნებით და ნაცხოვრები ეფექტით, რაც ტონალურ ლუქებს უფრო ბუნებრივს ხდის.',
        },
        material: { en: 'Garment-dyed cotton', ka: 'შეღებილი ბამბა' },
        care: { en: 'Wash separately on first use.', ka: 'პირველ რეცხვაზე გარეცხე ცალკე.' },
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Faded Ink', 'Dust', 'Olive Wash'],
        stock: 7,
        rating: 4.6,
        reviewCount: 58,
        tags: ['washed', 'tonal', 'soft'],
        images: [1, 3, 4],
      },
      {
        label: { en: 'Layering Tee', ka: 'საფენად მაისური' },
        price: 79,
        oldPrice: null,
        detail: {
          en: 'a longer hem and smooth drape intended for hoodies, jackets, and tailored layers.',
          ka: 'გრძელი ქვედა ხაზით და გლუვი დაცემით, შექმნილი ჰუდებთან, ქურთუკებთან და თარგიან ფენებთან შესახამებლად.',
        },
        material: { en: 'Lightweight mercerized cotton', ka: 'მსუბუქი მერსერიზებული ბამბა' },
        care: { en: 'Cold wash and hang to dry.', ka: 'გარეცხე ცივად და გააშრე საკიდზე.' },
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        colors: ['White', 'Slate', 'Taupe'],
        stock: 21,
        rating: 4.8,
        reviewCount: 91,
        tags: ['layering', 'longline', 'essential'],
        images: [0, 1, 4],
      },
    ],
  },
  {
    slug: 'jeans',
    name: { en: 'Jeans', ka: 'ჯინსები' },
    description: {
      en: 'Modern denim fits with clear rises, useful washes, and enough room to move.',
      ka: 'თანამედროვე დენიმის თარგები მკაფიო წელით, პრაქტიკული ფერებით და მოძრაობისთვის საკმარისი სივრცით.',
    },
    image: imagePools.jeans[0],
    featured: false,
    imagePool: imagePools.jeans,
    variants: [
      {
        label: { en: 'Straight Jeans', ka: 'სწორი ჯინსი' },
        price: 179,
        oldPrice: null,
        detail: {
          en: 'a balanced straight leg with a crisp break and clean top block.',
          ka: 'დაბალანსებული სწორი ტოტით, გამოკვეთილი დაცემით და სუფთა ზედა ნაწილით.',
        },
        material: { en: 'Rigid cotton denim', ka: 'მყარი ბამბის დენიმი' },
        care: { en: 'Spot clean when possible and wash inside out.', ka: 'შეძლებისდაგვარად ლაქობრივად გაწმინდე და გარეცხე შიგნიდან გადმობრუნებული.' },
        sizes: ['28', '30', '32', '34', '36'],
        colors: ['Raw Indigo', 'Washed Black', 'Mid Blue'],
        stock: 11,
        rating: 4.8,
        reviewCount: 102,
        tags: ['denim', 'straight', 'core'],
        images: [0, 1, 2],
      },
      {
        label: { en: 'Wide-Leg Jeans', ka: 'ფართო ტოტის ჯინსი' },
        price: 189,
        oldPrice: 225,
        detail: {
          en: 'expanded volume from hip to hem for a wide, city-ready shape.',
          ka: 'გაფართოებული მოცულობით თეძოდან ბოლომდე, ფართო და ქალაქისთვის მზად ფორმისთვის.',
        },
        material: { en: 'Structured cotton denim', ka: 'სტრუქტურირებული ბამბის დენიმი' },
        care: { en: 'Wash cold and avoid over-drying.', ka: 'გარეცხე ცივად და არ გადააშრო.' },
        sizes: ['26', '28', '30', '32', '34'],
        colors: ['Ink', 'Cloud Blue', 'Vintage Grey'],
        stock: 5,
        rating: 4.9,
        reviewCount: 67,
        tags: ['wide-leg', 'fashion', 'statement'],
        images: [1, 2, 3],
      },
      {
        label: { en: 'Tapered Jeans', ka: 'დავიწროებული ჯინსი' },
        price: 172,
        oldPrice: null,
        detail: {
          en: 'extra room through the thigh with a clean taper that works with simple sneakers.',
          ka: 'ბარძაყის არეში მეტი სივრცით და სუფთა შევიწროებით, რომელიც მარტივ სნიკერებს კარგად ერწყმის.',
        },
        material: { en: 'Stretch comfort denim', ka: 'კომფორტული გაწელვადი დენიმი' },
        care: { en: 'Wash with dark colors and hang dry.', ka: 'გარეცხე მუქ ფერებთან ერთად და გააშრე ჰაერზე.' },
        sizes: ['28', '30', '32', '34', '36'],
        colors: ['Charcoal', 'Blue Stone', 'Night'],
        stock: 16,
        rating: 4.7,
        reviewCount: 84,
        tags: ['tapered', 'smart casual', 'denim'],
        images: [0, 2, 4],
      },
      {
        label: { en: 'Washed Jeans', ka: 'დამუშავებული ჯინსი' },
        price: 165,
        oldPrice: 198,
        detail: {
          en: 'soft fading and a vintage mood that adds texture to minimalist styling.',
          ka: 'რბილი გახუნებით და ვინტაჟური განწყობით, რომელიც მინიმალისტურ სტილს ტექსტურას მატებს.',
        },
        material: { en: 'Washed cotton denim', ka: 'დამუშავებული ბამბის დენიმი' },
        care: { en: 'Cold wash separately for the first wear cycle.', ka: 'პირველი გამოყენების ციკლში გარეცხე ცალკე, ცივად.' },
        sizes: ['28', '30', '32', '34'],
        colors: ['Faded Blue', 'Stone Grey', 'Washed Coal'],
        stock: 9,
        rating: 4.6,
        reviewCount: 49,
        tags: ['washed', 'vintage', 'street'],
        images: [2, 3, 4],
      },
      {
        label: { en: 'Carpenter Jeans', ka: 'კარპენტერის ჯინსი' },
        price: 196,
        oldPrice: null,
        detail: {
          en: 'utility detailing, stronger seams, and a looser profile with fashion credibility.',
          ka: 'ფუნქციური დეტალებით, გამაგრებული ნაკერებით და თავისუფალი პროფილით, რომელსაც მოდური ხიბლი აქვს.',
        },
        material: { en: 'Heavy-duty cotton denim', ka: 'გამძლე მძიმე ბამბის დენიმი' },
        care: { en: 'Wash cold and reshape while damp.', ka: 'გარეცხე ცივად და სველ მდგომარეობაში მიეცი ფორმა.' },
        sizes: ['30', '32', '34', '36'],
        colors: ['Raw Black', 'Work Blue', 'Bone'],
        stock: 4,
        rating: 4.9,
        reviewCount: 38,
        tags: ['carpenter', 'utility', 'wide'],
        images: [1, 3, 4],
      },
    ],
  },
  {
    slug: 'jackets',
    name: { en: 'Jackets', ka: 'ქურთუკები' },
    description: {
      en: 'Outerwear with reliable structure, clean hardware, and weather-ready details.',
      ka: 'გარე ტანსაცმელი მყარი სტრუქტურით, სუფთა ფურნიტურით და ამინდზე მორგებული დეტალებით.',
    },
    image: imagePools.jackets[0],
    featured: true,
    imagePool: imagePools.jackets,
    variants: [
      {
        label: { en: 'Bomber Jacket', ka: 'ბომბერი ქურთუკი' },
        price: 299,
        oldPrice: null,
        detail: {
          en: 'a refined flight silhouette with compact volume and smooth matte finishing.',
          ka: 'დახვეწილი საავიაციო სილუეტით, კომპაქტური მოცულობით და გლუვი მქრქალი დასრულებით.',
        },
        material: { en: 'Satin technical shell', ka: 'ატლასისებრი ტექნიკური ზედაპირი' },
        care: { en: 'Dry clean or wipe clean only.', ka: 'მხოლოდ ქიმწმენდა ან ზედაპირული გაწმენდა.' },
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Jet', 'Olive', 'Stone'],
        stock: 7,
        rating: 4.9,
        reviewCount: 94,
        tags: ['bomber', 'outerwear', 'clean'],
        images: [0, 1, 2],
      },
      {
        label: { en: 'Coach Jacket', ka: 'ქოუჩ ქურთუკი' },
        price: 249,
        oldPrice: 289,
        detail: {
          en: 'a crisp snap front, easy drape, and subtle sheen that sharpens casual styling.',
          ka: 'მკვეთრი ღილებიანი წინა ნაწილი, მარტივი დაცემა და მსუბუქი ბზინვარება, რომელიც ყოველდღიურ სტილს უფრო დახვეწილს ხდის.',
        },
        material: { en: 'Water-resistant nylon', ka: 'წყალგამძლე ნეილონი' },
        care: { en: 'Cold wash and air dry only.', ka: 'გარეცხე ცივად და გააშრე მხოლოდ ჰაერზე.' },
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Midnight', 'Tan', 'Graphite'],
        stock: 10,
        rating: 4.7,
        reviewCount: 61,
        tags: ['coach', 'nylon', 'layering'],
        images: [1, 2, 3],
      },
      {
        label: { en: 'Denim Jacket', ka: 'დენიმის ქურთუკი' },
        price: 279,
        oldPrice: null,
        detail: {
          en: 'slightly oversized shoulders and rigid structure for a high-low styling anchor.',
          ka: 'ოდნავ გაზრდილი მხრებით და მყარი სტრუქტურით, რომელიც მაღალი და დაბალი სტილის ელემენტებს აერთიანებს.',
        },
        material: { en: 'Structured cotton denim', ka: 'სტრუქტურირებული ბამბის დენიმი' },
        care: { en: 'Wash sparingly and avoid direct sunlight when drying.', ka: 'გარეცხე იშვიათად და გაშრობისას მოერიდე პირდაპირ მზეს.' },
        sizes: ['S', 'M', 'L'],
        colors: ['Mid Blue', 'Black Fade', 'Ecru'],
        stock: 8,
        rating: 4.8,
        reviewCount: 73,
        tags: ['denim jacket', 'oversized', 'core'],
        images: [0, 2, 4],
      },
      {
        label: { en: 'Shell Jacket', ka: 'შელის ქურთუკი' },
        price: 319,
        oldPrice: null,
        detail: {
          en: 'technical seams, weather-ready trim, and a sharper line through the body.',
          ka: 'ტექნიკური ნაკერებით, ამინდზე ორიენტირებული დეტალებით და უფრო მკვეთრი ხაზით სხეულზე.',
        },
        material: { en: '3-layer bonded shell', ka: '3-ფენიანი bonded shell' },
        care: { en: 'Use mild detergent and skip softener.', ka: 'გამოიყენე მსუბუქი სარეცხი საშუალება და არ დაამატო დამარბილებელი.' },
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Storm', 'Sand', 'Ice Grey'],
        stock: 5,
        rating: 4.9,
        reviewCount: 44,
        tags: ['technical', 'shell', 'utility'],
        images: [1, 3, 4],
      },
      {
        label: { en: 'Utility Jacket', ka: 'უტილიტი ქურთუკი' },
        price: 289,
        oldPrice: 339,
        detail: {
          en: 'functional pockets, cleaner seams, and enough structure to elevate daily dressing.',
          ka: 'ფუნქციური ჯიბეებით, სუფთა ნაკერებით და საკმარისი სტრუქტურით, რომ ყოველდღიური ჩაცმა უფრო დახვეწილი გახდეს.',
        },
        material: { en: 'Cotton canvas with soft lining', ka: 'ბამბის კანვასი რბილი სარჩულით' },
        care: { en: 'Wash cold and remove hardware before cleaning.', ka: 'გარეცხე ცივად და გაწმენდამდე მოხსენი დამატებითი აქსესუარები.' },
        sizes: ['M', 'L', 'XL'],
        colors: ['Moss', 'Black', 'Sandstone'],
        stock: 3,
        rating: 4.8,
        reviewCount: 36,
        tags: ['utility', 'canvas', 'outerwear'],
        images: [0, 3, 4],
      },
    ],
  },
  {
    slug: 'pants',
    name: { en: 'Pants', ka: 'შარვლები' },
    description: {
      en: 'Pants with clean lines, comfortable movement, and enough structure for daily wear.',
      ka: 'შარვლები სუფთა ხაზებით, კომფორტული მოძრაობით და ყოველდღიური ტარებისთვის საკმარისი სტრუქტურით.',
    },
    image: imagePools.pants[0],
    featured: false,
    imagePool: imagePools.pants,
    variants: [
      {
        label: { en: 'Tailored Pants', ka: 'თარგიანი შარვალი' },
        price: 179,
        oldPrice: null,
        detail: {
          en: 'a clean front, relaxed rise, and subtle taper that works with sneakers or loafers.',
          ka: 'სუფთა წინა ნაწილით, მოდუნებული წელით და მსუბუქი შევიწროებით, რომელიც სნიკერებსაც და ლოფერებსაც უხდება.',
        },
        material: { en: 'Viscose-wool blend', ka: 'ვისკოზა-შალის ნაზავი' },
        care: { en: 'Dry clean recommended.', ka: 'რეკომენდებულია ქიმწმენდა.' },
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Black', 'Charcoal', 'Taupe'],
        stock: 13,
        rating: 4.8,
        reviewCount: 80,
        tags: ['tailored', 'smart', 'minimal'],
        images: [0, 1, 2],
      },
      {
        label: { en: 'Cargo Pants', ka: 'კარგო შარვალი' },
        price: 189,
        oldPrice: 219,
        detail: {
          en: 'larger utility pockets, articulated knees, and a cleaner taper than classic cargo fits.',
          ka: 'დიდი ფუნქციური ჯიბეებით, დამუშავებული მუხლებით და უფრო სუფთა შევიწროებით, ვიდრე კლასიკურ კარგო მოდელებში.',
        },
        material: { en: 'Cotton twill with stretch', ka: 'გაწელვადი ბამბის twill' },
        care: { en: 'Machine wash cold and hang dry.', ka: 'გარეცხე ცივად და გააშრე ჰაერზე.' },
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Olive', 'Black', 'Stone'],
        stock: 6,
        rating: 4.7,
        reviewCount: 65,
        tags: ['cargo', 'utility', 'streetwear'],
        images: [1, 2, 3],
      },
      {
        label: { en: 'Relaxed Pants', ka: 'მოდუნებული შარვალი' },
        price: 169,
        oldPrice: null,
        detail: {
          en: 'easy volume with a fluid drape that sharpens oversized tees and cropped jackets.',
          ka: 'მარტივი მოცულობით და თავისუფალი დაცემით, რომელიც oversized მაისურებსა და მოკლე ქურთუკებს აძლიერებს.',
        },
        material: { en: 'Soft draped twill', ka: 'რბილი დაცემის მქონე twill' },
        care: { en: 'Cold wash, steam to restore drape.', ka: 'გარეცხე ცივად, ორთქლით აღადგინე დაცემა.' },
        sizes: ['XS', 'S', 'M', 'L'],
        colors: ['Ink', 'Clay', 'Mushroom'],
        stock: 17,
        rating: 4.8,
        reviewCount: 58,
        tags: ['relaxed', 'drape', 'easy'],
        images: [0, 2, 4],
      },
      {
        label: { en: 'Wide Pants', ka: 'ფართო შარვალი' },
        price: 182,
        oldPrice: 205,
        detail: {
          en: 'longer, sweeping volume that creates movement and length in monochrome looks.',
          ka: 'გრძელი, მოძრავი მოცულობით, რომელიც მონოქრომულ ლუქებს მოძრაობასა და სიგრძეს მატებს.',
        },
        material: { en: 'Textured suiting blend', ka: 'ტექსტურიანი საკოსტიუმე ნაზავი' },
        care: { en: 'Dry clean or cool hand wash.', ka: 'ქიმწმენდა ან გრილი ხელით რეცხვა.' },
        sizes: ['S', 'M', 'L'],
        colors: ['Coal', 'Oyster', 'Espresso'],
        stock: 5,
        rating: 4.9,
        reviewCount: 47,
        tags: ['wide', 'fashion', 'tailoring'],
        images: [1, 3, 4],
      },
      {
        label: { en: 'Track Pants', ka: 'ტრეკ შარვალი' },
        price: 159,
        oldPrice: null,
        detail: {
          en: 'a neat sports line with clean trim and a sharper shape than classic athleisure.',
          ka: 'მოწესრიგებული სპორტული ხაზით, სუფთა მოპირკეთებით და უფრო მკაფიო ფორმით, ვიდრე ჩვეულებრივ სპორტულ ყოველდღიურ სტილს.',
        },
        material: { en: 'Technical stretch jersey', ka: 'ტექნიკური გაწელვადი ჯერსი' },
        care: { en: 'Machine wash cold; do not iron trim.', ka: 'გარეცხე ცივად; არ გააუთაო მოპირკეთება.' },
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Black', 'Graphite', 'Navy'],
        stock: 20,
        rating: 4.7,
        reviewCount: 89,
        tags: ['track', 'technical', 'everyday'],
        images: [0, 1, 4],
      },
    ],
  },
  {
    slug: 'shorts',
    name: { en: 'Shorts', ka: 'შორტები' },
    description: {
      en: 'Shorts with breathable fabrics, clean hems, and practical pockets.',
      ka: 'შორტები სუნთქვადი ქსოვილით, სუფთა დაბოლოებით და პრაქტიკული ჯიბეებით.',
    },
    image: imagePools.shorts[0],
    featured: false,
    imagePool: imagePools.shorts,
    variants: [
      {
        label: { en: 'Cargo Shorts', ka: 'კარგო შორტი' },
        price: 129,
        oldPrice: 149,
        detail: {
          en: 'utility pockets and a neat hem that keep the shape clean rather than bulky.',
          ka: 'ფუნქციური ჯიბეებით და სუფთა დაბოლოებით, რაც ფორმას დამძიმების ნაცვლად მოწესრიგებულს ტოვებს.',
        },
        material: { en: 'Cotton ripstop', ka: 'ბამბის ripstop' },
        care: { en: 'Cold wash and reshape while damp.', ka: 'გარეცხე ცივად და სველ მდგომარეობაში მიეცი ფორმა.' },
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Sand', 'Olive', 'Black'],
        stock: 10,
        rating: 4.6,
        reviewCount: 44,
        tags: ['cargo', 'summer', 'utility'],
        images: [0, 1, 2],
      },
      {
        label: { en: 'Tailored Shorts', ka: 'თარგიანი შორტი' },
        price: 139,
        oldPrice: null,
        detail: {
          en: 'pleated ease and a polished rise for pairing with open shirts or slim knits.',
          ka: 'ნაკეციანი თავისუფლებით და დახვეწილი წელის ხაზით, იდეალურია გახსნილ პერანგებთან ან თხელ ნაქსოვ ზედებთან.',
        },
        material: { en: 'Structured twill blend', ka: 'სტრუქტურირებული twill ნაზავი' },
        care: { en: 'Dry clean or delicate cold wash.', ka: 'ქიმწმენდა ან ნაზი ცივი რეცხვა.' },
        sizes: ['S', 'M', 'L'],
        colors: ['Bone', 'Charcoal', 'Espresso'],
        stock: 8,
        rating: 4.8,
        reviewCount: 39,
        tags: ['tailored', 'smart summer', 'clean'],
        images: [1, 2, 3],
      },
      {
        label: { en: 'Nylon Shorts', ka: 'ნეილონის შორტი' },
        price: 119,
        oldPrice: null,
        detail: {
          en: 'sporty texture, lightweight comfort, and a crisp finish for active city days.',
          ka: 'სპორტული ტექსტურით, მსუბუქი კომფორტით და სუფთა დასრულებით აქტიური ქალაქური დღეებისთვის.',
        },
        material: { en: 'Lightweight technical nylon', ka: 'მსუბუქი ტექნიკური ნეილონი' },
        care: { en: 'Wash cold and avoid high heat.', ka: 'გარეცხე ცივად და მოერიდე მაღალ სიცხეს.' },
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Graphite', 'Navy', 'Khaki'],
        stock: 13,
        rating: 4.7,
        reviewCount: 53,
        tags: ['nylon', 'technical', 'summer'],
        images: [0, 2, 4],
      },
      {
        label: { en: 'Sweat Shorts', ka: 'სვეათ შორტი' },
        price: 109,
        oldPrice: 129,
        detail: {
          en: 'soft fleece handfeel and a sturdy waistband that keeps loungewear looking sharp.',
          ka: 'რბილი ფლისის შეგრძნებით და მყარი წელის ხაზით, რომელიც სახლის სტილს უფრო მოწესრიგებულს აჩენს.',
        },
        material: { en: 'Brushed cotton fleece', ka: 'დავარცხნილი ბამბის ფლისი' },
        care: { en: 'Machine wash cold and line dry.', ka: 'გარეცხე ცივად და გააშრე ჰაერზე.' },
        sizes: ['S', 'M', 'L', 'XL'],
        colors: ['Heather', 'Jet', 'Cream'],
        stock: 15,
        rating: 4.6,
        reviewCount: 64,
        tags: ['sweat shorts', 'lounge', 'essential'],
        images: [1, 3, 4],
      },
      {
        label: { en: 'Denim Shorts', ka: 'დენიმის შორტი' },
        price: 135,
        oldPrice: null,
        detail: {
          en: 'a cleaner denim cut with enough room for relaxed styling and simple sandals.',
          ka: 'უფრო სუფთა დენიმის თარგით, საკმარისი სივრცით თავისუფალი სტილისა და მარტივი სანდლებისთვის.',
        },
        material: { en: 'Washed cotton denim', ka: 'დამუშავებული ბამბის დენიმი' },
        care: { en: 'Wash sparingly and dry away from sunlight.', ka: 'გარეცხე იშვიათად და გააშრე მზისგან მოშორებით.' },
        sizes: ['28', '30', '32', '34'],
        colors: ['Blue Wash', 'Black Wash', 'Ecru'],
        stock: 7,
        rating: 4.8,
        reviewCount: 42,
        tags: ['denim', 'shorts', 'washed'],
        images: [0, 3, 4],
      },
    ],
  },
  {
    slug: 'dresses',
    name: { en: 'Dresses', ka: 'კაბები' },
    description: {
      en: 'Dresses with comfortable movement, clean lines, and fabrics that feel good on skin.',
      ka: 'კაბები კომფორტული მოძრაობით, სუფთა ხაზებით და კანზე სასიამოვნო ქსოვილებით.',
    },
    image: imagePools.dresses[0],
    featured: true,
    imagePool: imagePools.dresses,
    variants: [
      {
        label: { en: 'Slip Dress', ka: 'სლიპ კაბა' },
        price: 239,
        oldPrice: null,
        detail: {
          en: 'bias-cut movement and slim straps that create a clean, evening-ready line.',
          ka: 'დახრილი ჭრის დაცემით და წვრილი სამხრეებით, რომლებიც სუფთა, საღამოსთვის მზა ხაზს ქმნის.',
        },
        material: { en: 'Satin viscose blend', ka: 'ატლასისებრი ვისკოზის ნაზავი' },
        care: { en: 'Dry clean only.', ka: 'მხოლოდ ქიმწმენდა.' },
        sizes: ['XS', 'S', 'M', 'L'],
        colors: ['Black', 'Champagne', 'Olive'],
        stock: 9,
        rating: 4.9,
        reviewCount: 77,
        tags: ['slip dress', 'evening', 'minimal'],
        images: [0, 1, 2],
      },
      {
        label: { en: 'Rib Dress', ka: 'რიბ კაბა' },
        price: 189,
        oldPrice: 225,
        detail: {
          en: 'body-skimming texture, easy stretch, and a longer hem for effortless polish.',
          ka: 'სხეულის მიმყოლი ტექსტურით, მარტივი ელასტიურობით და უფრო გრძელი ბოლოს ხაზით ძალდაუტანებელი სისუფთავისთვის.',
        },
        material: { en: 'Soft rib knit', ka: 'რბილი რიბ-ნაქსოვი' },
        care: { en: 'Hand wash cold and lay flat.', ka: 'ხელით გარეცხე ცივად და გააშრე სწორ ზედაპირზე.' },
        sizes: ['XS', 'S', 'M', 'L'],
        colors: ['Chocolate', 'Stone', 'Jet'],
        stock: 11,
        rating: 4.8,
        reviewCount: 59,
        tags: ['rib', 'day to night', 'knit'],
        images: [1, 2, 3],
      },
      {
        label: { en: 'Satin Dress', ka: 'ატლასის კაბა' },
        price: 259,
        oldPrice: null,
        detail: {
          en: 'liquid shine and fuller drape for events that call for quiet drama.',
          ka: 'თხევადი ბზინვარებით და უფრო მდიდარი დაცემით იმ შემთხვევებისთვის, სადაც მშვიდი დრამატულობა საჭიროა.',
        },
        material: { en: 'Heavy satin weave', ka: 'მკვრივი ატლასის ქსოვა' },
        care: { en: 'Dry clean recommended.', ka: 'რეკომენდებულია ქიმწმენდა.' },
        sizes: ['S', 'M', 'L'],
        colors: ['Midnight', 'Pearl', 'Forest'],
        stock: 6,
        rating: 4.9,
        reviewCount: 43,
        tags: ['satin', 'occasion', 'evening'],
        images: [0, 2, 4],
      },
      {
        label: { en: 'Shirt Dress', ka: 'პერანგის კაბა' },
        price: 219,
        oldPrice: 249,
        detail: {
          en: 'crisp lines, beltable volume, and a polished collar for modern versatility.',
          ka: 'მკვეთრი ხაზებით, სარტყელისთვის შესაფერისი მოცულობით და დახვეწილი საყელოთი თანამედროვე მრავალფეროვნებისთვის.',
        },
        material: { en: 'Crisp cotton poplin', ka: 'მკვეთრი ბამბის poplin' },
        care: { en: 'Cold wash and steam lightly.', ka: 'გარეცხე ცივად და მსუბუქად გაუშვი ორთქლი.' },
        sizes: ['XS', 'S', 'M', 'L'],
        colors: ['White', 'Sky', 'Sand'],
        stock: 8,
        rating: 4.7,
        reviewCount: 48,
        tags: ['shirt dress', 'smart', 'versatile'],
        images: [1, 3, 4],
      },
      {
        label: { en: 'Column Dress', ka: 'სვეტის კაბა' },
        price: 245,
        oldPrice: null,
        detail: {
          en: 'a pared-back longline shape with enough structure to feel architectural.',
          ka: 'მინიმალისტური გრძელი სილუეტით და იმდენი სტრუქტურით, რომ არქიტექტურულად იგრძნობოდეს.',
        },
        material: { en: 'Structured stretch crepe', ka: 'სტრუქტურირებული stretch crepe' },
        care: { en: 'Dry clean or hand wash with care.', ka: 'ქიმწმენდა ან ფრთხილი ხელით რეცხვა.' },
        sizes: ['XS', 'S', 'M', 'L'],
        colors: ['Onyx', 'Clay', 'Taupe'],
        stock: 5,
        rating: 4.8,
        reviewCount: 34,
        tags: ['column', 'architectural', 'clean'],
        images: [0, 3, 4],
      },
    ],
  },
  {
    slug: 'accessories',
    name: { en: 'Accessories', ka: 'აქსესუარები' },
    description: {
      en: 'Useful finishing pieces with good texture, simple branding, and everyday function.',
      ka: 'პრაქტიკული აქსესუარები კარგი ტექსტურით, მარტივი ბრენდირებით და ყოველდღიური ფუნქციით.',
    },
    image: imagePools.accessories[0],
    featured: false,
    imagePool: imagePools.accessories,
    variants: [
      {
        label: { en: 'Tote Bag', ka: 'ტოტე ჩანთა' },
        price: 145,
        oldPrice: null,
        detail: {
          en: 'roomy proportions, reinforced handles, and a sharp silhouette for everyday carry.',
          ka: 'ტევადი პროპორციებით, გამაგრებული სახელურებით და მკვეთრი ფორმით ყოველდღიური გამოყენებისთვის.',
        },
        material: { en: 'Structured canvas', ka: 'სტრუქტურირებული კანვასი' },
        care: { en: 'Spot clean only.', ka: 'მხოლოდ ზედაპირული წმენდა.' },
        sizes: ['One Size'],
        colors: ['Black', 'Sand', 'Olive'],
        stock: 16,
        rating: 4.8,
        reviewCount: 82,
        tags: ['tote', 'bag', 'everyday'],
        images: [0, 1, 2],
      },
      {
        label: { en: 'Beanie', ka: 'ბინი' },
        price: 69,
        oldPrice: 85,
        detail: {
          en: 'dense knit texture and a clean fold that looks neat rather than sporty.',
          ka: 'მკვრივი ნაქსოვი ტექსტურით და სუფთა გადაკეცვით, რომელიც სპორტულის ნაცვლად მოწესრიგებულად ჩანს.',
        },
        material: { en: 'Merino blend knit', ka: 'მერინოს ნაზავის ნაქსოვი' },
        care: { en: 'Hand wash cold and dry flat.', ka: 'ხელით გარეცხე ცივად და გააშრე სწორ ზედაპირზე.' },
        sizes: ['One Size'],
        colors: ['Coal', 'Bone', 'Moss'],
        stock: 23,
        rating: 4.7,
        reviewCount: 57,
        tags: ['beanie', 'winter', 'essential'],
        images: [1, 2, 3],
      },
      {
        label: { en: 'Cap', ka: 'ქუდი' },
        price: 75,
        oldPrice: null,
        detail: {
          en: 'curved peak, tonal embroidery, and a stronger crown shape for cleaner styling.',
          ka: 'მომრგვალებული წინით, ტონალური ქარგვით და გამოკვეთილი ზედა ნაწილით უფრო სუფთა სტილისთვის.',
        },
        material: { en: 'Cotton twill', ka: 'ბამბის twill' },
        care: { en: 'Hand wash and air dry.', ka: 'ხელით გარეცხე და გააშრე ჰაერზე.' },
        sizes: ['One Size'],
        colors: ['Black', 'Taupe', 'Navy'],
        stock: 19,
        rating: 4.6,
        reviewCount: 41,
        tags: ['cap', 'streetwear', 'logo'],
        images: [0, 2, 4],
      },
      {
        label: { en: 'Scarf', ka: 'შარფი' },
        price: 95,
        oldPrice: null,
        detail: {
          en: 'soft handfeel, tonal fringe, and enough weight to anchor winter outerwear.',
          ka: 'რბილი შეგრძნებით, ტონალური ფოჩებით და საკმარისი სიმძიმით ზამთრის გარე ტანსაცმლის დასაბალანსებლად.',
        },
        material: { en: 'Wool-touch blend', ka: 'შალის შეგრძნების ნაზავი' },
        care: { en: 'Dry clean recommended.', ka: 'რეკომენდებულია ქიმწმენდა.' },
        sizes: ['One Size'],
        colors: ['Grey', 'Camel', 'Black'],
        stock: 12,
        rating: 4.8,
        reviewCount: 33,
        tags: ['scarf', 'winter', 'soft'],
        images: [1, 3, 4],
      },
      {
        label: { en: 'Belt', ka: 'ქამარი' },
        price: 105,
        oldPrice: 129,
        detail: {
          en: 'clean hardware and a slim profile that works across dresses, denim, and tailoring.',
          ka: 'სუფთა მეტალის დეტალებით და თხელი პროფილით, რომელიც კაბებს, დენიმსა და თარგიან შარვლებს ერთნაირად უხდება.',
        },
        material: { en: 'Full-grain leather', ka: 'მაღალი ხარისხის ტყავი' },
        care: { en: 'Wipe clean and condition occasionally.', ka: 'გაწმინდე ნესტიანი ტილოთი და პერიოდულად დაამუშავე კონდიციონერით.' },
        sizes: ['S', 'M', 'L'],
        colors: ['Black', 'Brown', 'Sand'],
        stock: 9,
        rating: 4.9,
        reviewCount: 29,
        tags: ['belt', 'leather', 'clean'],
        images: [0, 3, 4],
      },
    ],
  },
  {
    slug: 'shoes',
    name: { en: 'Shoes', ka: 'ფეხსაცმელი' },
    description: {
      en: 'Footwear with comfortable soles, simple branding, and materials that hold up well.',
      ka: 'ფეხსაცმელი კომფორტული ძირებით, მარტივი ბრენდირებით და გამძლე მასალებით.',
    },
    image: imagePools.shoes[0],
    featured: true,
    imagePool: imagePools.shoes,
    variants: [
      {
        label: { en: 'Leather Sneakers', ka: 'ტყავის სნიკერები' },
        price: 329,
        oldPrice: null,
        detail: {
          en: 'clean panels, smooth leather, and a cushioned sole for all-day wear.',
          ka: 'სუფთა პანელებით, გლუვი ტყავით და რბილი ძირით, რომელიც მთელი დღის კომფორტს ინარჩუნებს.',
        },
        material: { en: 'Full-grain leather upper', ka: 'მაღალი ხარისხის ტყავის ზედაპირი' },
        care: { en: 'Wipe clean and use leather protector.', ka: 'გაწმინდე ნესტიანი ტილოთი და გამოიყენე ტყავის დამცავი საშუალება.' },
        sizes: ['39', '40', '41', '42', '43', '44'],
        colors: ['White', 'Black', 'Sand'],
        stock: 10,
        rating: 4.9,
        reviewCount: 118,
        tags: ['sneakers', 'leather', 'daily'],
        images: [0, 1, 2],
      },
      {
        label: { en: 'Running Sneakers', ka: 'სარბენი სნიკერები' },
        price: 289,
        oldPrice: 329,
        detail: {
          en: 'lightweight cushioning and a fast profile tuned for movement and daily wear.',
          ka: 'მსუბუქი ამორტიზაციით და სწრაფი პროფილით, მორგებული მოძრაობასა და ყოველდღიურ ტარებაზე.',
        },
        material: { en: 'Technical mesh with suede trim', ka: 'ტექნიკური ბადე ზამშის დეტალებით' },
        care: { en: 'Clean with soft brush and air dry.', ka: 'გაწმინდე რბილი ჯაგრისით და გააშრე ჰაერზე.' },
        sizes: ['39', '40', '41', '42', '43', '44'],
        colors: ['Silver', 'Graphite', 'Sage'],
        stock: 14,
        rating: 4.8,
        reviewCount: 92,
        tags: ['running', 'technical', 'comfort'],
        images: [1, 2, 3],
      },
      {
        label: { en: 'High-Top Sneakers', ka: 'მაღალყელიანი სნიკერები' },
        price: 309,
        oldPrice: null,
        detail: {
          en: 'higher ankle coverage and a bold shape that pairs naturally with wide denim.',
          ka: 'მაღალი ყელის დაფარვით და გამოკვეთილი ფორმით, რომელიც ფართო დენიმს ბუნებრივად ეხამება.',
        },
        material: { en: 'Canvas and leather mix', ka: 'კანვასისა და ტყავის კომბინაცია' },
        care: { en: 'Spot clean and avoid soaking.', ka: 'გაწმინდე ლაქობრივად და არ დაალბო.' },
        sizes: ['39', '40', '41', '42', '43'],
        colors: ['Black', 'Bone', 'Olive'],
        stock: 7,
        rating: 4.7,
        reviewCount: 46,
        tags: ['high-top', 'streetwear', 'statement'],
        images: [0, 2, 4],
      },
      {
        label: { en: 'Slides', ka: 'სლაიდები' },
        price: 149,
        oldPrice: 179,
        detail: {
          en: 'tonal branding, a shaped footbed, and a comfortable lounge feel.',
          ka: 'ტონალური ბრენდირებით, ანატომიური ძირით და კომფორტული დასასვენებელი შეგრძნებით.',
        },
        material: { en: 'Molded EVA with soft strap', ka: 'ჩამოსხმული EVA რბილი სამაგრით' },
        care: { en: 'Rinse clean and dry in shade.', ka: 'გაწმინდე წყლით და გააშრე ჩრდილში.' },
        sizes: ['39', '40', '41', '42', '43', '44'],
        colors: ['Black', 'Bone', 'Khaki'],
        stock: 18,
        rating: 4.6,
        reviewCount: 54,
        tags: ['slides', 'summer', 'comfort'],
        images: [1, 3, 4],
      },
      {
        label: { en: 'Chelsea Boots', ka: 'ჩელსი ბოტები' },
        price: 359,
        oldPrice: null,
        detail: {
          en: 'sleek elastic side panels and a sharper sole profile for simple evening styling.',
          ka: 'გლუვი ელასტიკური გვერდებით და მკვეთრი ძირის პროფილით მარტივი საღამოს სტილისთვის.',
        },
        material: { en: 'Polished leather upper', ka: 'დაპრიალებული ტყავის ზედაპირი' },
        care: { en: 'Wipe clean, polish lightly, and store with shoe trees.', ka: 'გაწმინდე, მსუბუქად გააპრიალე და შეინახე ფორმის დამჭერით.' },
        sizes: ['40', '41', '42', '43', '44'],
        colors: ['Black', 'Espresso'],
        stock: 5,
        rating: 4.9,
        reviewCount: 31,
        tags: ['chelsea', 'boots', 'evening'],
        images: [0, 3, 4],
      },
    ],
  },
];

const productGenderMatrix: Record<CategorySlug, ProductGender[]> = {
  hoodies: ['unisex', 'men', 'men', 'women', 'men'],
  't-shirts': ['unisex', 'men', 'women', 'unisex', 'women'],
  jeans: ['unisex', 'women', 'men', 'women', 'men'],
  jackets: ['unisex', 'men', 'unisex', 'women', 'men'],
  pants: ['women', 'men', 'unisex', 'women', 'men'],
  shorts: ['men', 'women', 'unisex', 'unisex', 'women'],
  dresses: ['women', 'women', 'women', 'women', 'women'],
  accessories: ['unisex', 'unisex', 'unisex', 'women', 'unisex'],
  shoes: ['unisex', 'unisex', 'men', 'unisex', 'men'],
};

const buildProduct = (category: CategorySeed, variant: VariantSeed, index: number): Product => {
  const line = series[index];
  const slug = toSlug(`${line.title.en}-${variant.label.en}`);

  return {
    id: slug,
    slug,
    sku: `${category.slug.slice(0, 3).toUpperCase()}-${(index + 1).toString().padStart(2, '0')}`,
    name: {
      en: `${line.title.en} ${variant.label.en}`,
      ka: `${line.title.ka} ${variant.label.ka}`,
    },
    category: category.slug,
    gender: productGenderMatrix[category.slug][index] ?? 'unisex',
    price: variant.price,
    oldPrice: variant.oldPrice,
    description: {
      en: `${line.title.en} ${variant.label.en} is ${line.tagline.en} Details include ${variant.detail.en}`,
      ka: `${line.title.ka} ${variant.label.ka} ${line.tagline.ka} გამოირჩევა ${variant.detail.ka}`,
    },
    material: variant.material,
    careInstructions: variant.care,
    sizes: variant.sizes,
    colors: variant.colors,
    stock: variant.stock,
    rating: variant.rating,
    reviewCount: variant.reviewCount,
    tags: [...variant.tags, category.slug, line.title.en],
    images: variant.images.map((imageIndex) => category.imagePool[imageIndex] ?? category.imagePool[0]),
    flags: {
      isFeatured: index === 0 || (category.featured && index < 2),
      isNew: index === 1 || index === 4,
      isSale: variant.oldPrice !== null,
    },
    popularity: Math.round(variant.rating * 20 + variant.reviewCount / 2),
    createdAt: new Date(2026, 3, 29 - index).toISOString(),
  };
};

export const demoCategories: Category[] = categorySeeds.map((category, index) => ({
  id: `${category.slug}-${index}`,
  slug: category.slug,
  name: category.name,
  description: category.description,
  image: category.image,
  featured: category.featured,
}));

export const demoProducts: Product[] = categorySeeds.flatMap((category) =>
  category.variants.map((variant, index) => buildProduct(category, variant, index)),
);

export const homeGallery = [
  'https://images.unsplash.com/photo-1445205170230-053b83016050?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=80',
  'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=80',
];

export const testimonials = [
  {
    id: '1',
    name: 'Nina G.',
    role: { en: 'Creative director', ka: 'კრეატიული დირექტორი' },
    quote: {
      en: 'The fit is clean, the fabric feels good, and the pieces are easy to wear outside a photoshoot.',
      ka: 'თარგი სუფთაა, ქსოვილი სასიამოვნოა და ნივთები ფოტოსესიის გარეშეც მარტივად იცმევა.',
    },
  },
  {
    id: '2',
    name: 'Luka T.',
    role: { en: 'Stylist', ka: 'სტილისტი' },
    quote: {
      en: 'The layering pieces are useful. They look considered without shouting for attention.',
      ka: 'ფენებად ჩასაცმელი ნივთები ნამდვილად პრაქტიკულია. იერი გააზრებულია და ზედმეტად არ ყვირის.',
    },
  },
  {
    id: '3',
    name: 'Mariam K.',
    role: { en: 'Fashion buyer', ka: 'მოდის ბაიერი' },
    quote: {
      en: 'The catalog is clear, the sizing is easy to understand, and checkout feels straightforward.',
      ka: 'კატალოგი გასაგებია, ზომები მარტივად იკითხება და შეკვეთის გაფორმება პირდაპირია.',
    },
  },
];

export const reviewTemplates: Review[] = [
  {
    id: 'rev-1',
    author: 'Natia',
    rating: 5,
    title: { en: 'Good fit and feel', ka: 'კარგი თარგი და შეგრძნება' },
    body: {
      en: 'The fabric feels solid, the silhouette sits well, and the finishing is clean all around.',
      ka: 'ქსოვილი შეხებით ხარისხიანია, სილუეტი კარგად ჯდება და დასრულება ყველა მხრიდან სუფთაა.',
    },
  },
  {
    id: 'rev-2',
    author: 'Alex',
    rating: 5,
    title: { en: 'Better in person', ka: 'რეალურად უკეთესია' },
    body: {
      en: 'I styled it a few different ways and it still felt easy to wear.',
      ka: 'რამდენიმე განსხვავებულად ჩავიცვი და მაინც მარტივად სატარებელი დარჩა.',
    },
  },
  {
    id: 'rev-3',
    author: 'Tamo',
    rating: 4,
    title: { en: 'Strong details', ka: 'ძლიერი დეტალები' },
    body: {
      en: 'The proportions and materials are what stand out most. It feels carefully designed.',
      ka: 'ყველაზე მეტად პროპორციები და მასალები გამოირჩევა. აშკარად გააზრებული დიზაინია.',
    },
  },
];

export const heroStats = [
  { value: '45', label: { en: 'Curated products', ka: 'შერჩეული პროდუქტი' } },
  { value: '9', label: { en: 'Style categories', ka: 'სტილის კატეგორია' } },
  { value: '24h', label: { en: 'Fast dispatch target', ka: 'სწრაფი გაგზავნის მიზანი' } },
];
